server:
  port: 8080
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root:INFO

info:
  app:
    name:@project.artifactId@
    encoding:@project.build.sourceEncoding@
    "java":{
        "source":"1.8.1",
        "target":"1.8.1"

    }



